# Generated by Django 2.2 on 2020-12-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress_bar',
            field=models.FloatField(default=0),
        ),
    ]
