# Generated by Django 2.2 on 2020-12-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20201224_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='balance_payment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='part_payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
