# Generated by Django 2.2 on 2020-12-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20201224_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
