# Generated by Django 2.2 on 2020-12-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_auto_20201224_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='full_names',
            field=models.CharField(max_length=150),
        ),
    ]
