# Generated by Django 2.2 on 2020-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_project_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_to_content_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('initilizing', 'initilizing'), ('Started', 'Started'), ('Inprogress', 'Inprogress'), ('Testing', 'Testing'), ('Completed', 'Completed'), ('full_payment_made', 'full_payment_made'), ('Terminated', 'Terminated')], help_text='initilizing', max_length=30, null=True),
        ),
    ]
