# Generated by Django 2.2 on 2020-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_auto_20201230_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('initilizing', 'initilizing'), ('Started', 'Started'), ('Inprogress', 'Inprogress'), ('Testing', 'Testing'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], help_text='initilizing', max_length=30, null=True),
        ),
    ]
