# Generated by Django 2.2 on 2020-12-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_auto_20201230_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_started',
            field=models.BooleanField(default=False),
        ),
    ]
