# Generated by Django 2.2 on 2020-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_auto_20201230_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_testing',
            field=models.BooleanField(default=False),
        ),
    ]
