# Generated by Django 2.2 on 2020-12-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0010_project_project_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='client',
        ),
    ]
