# Generated by Django 2.2 on 2021-01-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0012_credentials_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
