# Generated by Django 2.2 on 2021-01-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_testimony_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='testimony',
            field=models.TextField(max_length=200),
        ),
    ]
